services:
  # Backend service
  - type: web
    name: contest-tracker-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: contest-tracker-db
          property: connectionString

  # Frontend service
  - type: web
    name: contest-tracker-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: contest-tracker-db
    databaseName: contest_tracker
    user: contest_tracker_user